[build-system]
requires = ["setuptools","black"]
build-backend = "setuptools.build_meta"

[project]
name = "primaryschool.pssettings.app_name"
description = "Primaryschool knowledge games."
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
keywords = ["gui", "education", "games"]
authors = "primaryschool.pssettings.app_contributors"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Students",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Games",
]
dependencies = 'primaryschool.psdep.req_names_with_version_pypi'

[dynamic]
version = "primaryschool.pssettings.app_version"

[project.urls]
Homepage = "primaryschool.pssettings.app_url"

[tool.setuptools.packages.find]
where = ["primaryschool"]

[tool.black]
line-length = 79
target-version = ["py36", "py37", "py38", "py39", "py310"]
include = '\\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
