[build-system]
requires = ["setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = ""
description = ""
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
keywords = [ "education", "game"]
authors = []
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Students",
  "Topic :: Games",
]
dependencies = []

[project.urls]
Source = ""

[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.exclude-package-data]
"*" = ["*.pot", "*.po"]

[project.gui-scripts]
primaryschool = "primaryschool"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = [ "*.mo",]
